from sqlalchemy import Column, Integer, String, Float  # Importing Float here
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), nullable=False)
    email = Column(String(50), unique=True, index=True)

class PlayerBoxScore(Base):
    __tablename__ = 'player_box_score'

    game_id = Column(Integer, primary_key=True, index=True)
    athlete_id = Column(Integer, primary_key=True, index=True)  # Composite primary key with `game_id`
    season = Column(Integer, nullable=True)
    season_type = Column(Integer, nullable=True)
    game_date = Column(String(255), nullable=True)
    game_date_time = Column(String(255), nullable=True)
    athlete_display_name = Column(String(255), nullable=True)
    team_id = Column(Integer, nullable=True)
    team_name = Column(String(255), nullable=True)
    team_location = Column(String(255), nullable=True)
    team_short_display_name = Column(String(255), nullable=True)
    minutes = Column(Float, nullable=True)  # Now using Float, correctly imported
    field_goals_made = Column(Integer, nullable=True)
    field_goals_attempted = Column(Integer, nullable=True)
    three_point_field_goals_made = Column(Integer, nullable=True)
    three_point_field_goals_attempted = Column(Integer, nullable=True)
    free_throws_made = Column(Integer, nullable=True)
    free_throws_attempted = Column(Integer, nullable=True)
    offensive_rebounds = Column(Integer, nullable=True)
    defensive_rebounds = Column(Integer, nullable=True)
    rebounds = Column(Integer, nullable=True)
    assists = Column(Integer, nullable=True)
    steals = Column(Integer, nullable=True)
    blocks = Column(Integer, nullable=True)
    turnovers = Column(Integer, nullable=True)
    fouls = Column(Integer, nullable=True)
    points = Column(Integer, nullable=True)
    starter = Column(String(255), nullable=True)
    ejected = Column(String(255), nullable=True)
    did_not_play = Column(String(255), nullable=True)
    active = Column(String(255), nullable=True)
    athlete_jersey = Column(Integer, nullable=True)
    athlete_short_name = Column(String(255), nullable=True)
    athlete_headshot_href = Column(String(255), nullable=True)
    athlete_position_name = Column(String(255), nullable=True)
    athlete_position_abbreviation = Column(String(255), nullable=True)
    team_display_name = Column(String(255), nullable=True)
    team_uid = Column(String(255), nullable=True)
    team_slug = Column(String(255), nullable=True)
    team_logo = Column(String(255), nullable=True)
    team_abbreviation = Column(String(255), nullable=True)
    team_color = Column(String(255), nullable=True)
    team_alternate_color = Column(String(255), nullable=True)
    home_away = Column(String(255), nullable=True)
    team_winner = Column(String(255), nullable=True)
    team_score = Column(Integer, nullable=True)
    opponent_team_id = Column(Integer, nullable=True)
    opponent_team_name = Column(String(255), nullable=True)
    opponent_team_location = Column(String(255), nullable=True)
    opponent_team_display_name = Column(String(255), nullable=True)
    opponent_team_abbreviation = Column(String(255), nullable=True)
    opponent_team_logo = Column(String(255), nullable=True)
    opponent_team_color = Column(String(255), nullable=True)
    opponent_team_alternate_color = Column(String(255), nullable=True)
    opponent_team_score = Column(Integer, nullable=True)

class TeamBoxScore(Base):
    __tablename__ = 'team_box_score'

    game_id = Column(Integer, primary_key=True, index=True)
    season = Column(Integer, nullable=True)
    season_type = Column(Integer, nullable=True)
    game_date = Column(String(255), nullable=True)
    game_date_time = Column(String(255), nullable=True)
    team_id = Column(Integer, nullable=False)
    team_uid = Column(String(255), nullable=True)
    team_slug = Column(String(255), nullable=True)
    team_location = Column(String(255), nullable=True)
    team_name = Column(String(255), nullable=True)
    team_abbreviation = Column(String(255), nullable=True)
    team_display_name = Column(String(255), nullable=True)
    team_short_display_name = Column(String(255), nullable=True)
    team_color = Column(String(255), nullable=True)
    team_alternate_color = Column(String(255), nullable=True)
    team_logo = Column(String(255), nullable=True)
    team_home_away = Column(String(255), nullable=True)
    team_score = Column(Integer, nullable=True)
    team_winner = Column(String(255), nullable=True)
    assists = Column(Integer, nullable=True)
    blocks = Column(Integer, nullable=True)
    defensive_rebounds = Column(Integer, nullable=True)
    fast_break_points = Column(Integer, nullable=True)
    field_goal_pct = Column(Float, nullable=True)
    field_goals_made = Column(Integer, nullable=True)
    field_goals_attempted = Column(Integer, nullable=True)
    flagrant_fouls = Column(Integer, nullable=True)
    fouls = Column(Integer, nullable=True)
    free_throw_pct = Column(Float, nullable=True)
    free_throws_made = Column(Integer, nullable=True)
    free_throws_attempted = Column(Integer, nullable=True)
    largest_lead = Column(Integer, nullable=True)
    offensive_rebounds = Column(Integer, nullable=True)
    points_in_paint = Column(Integer, nullable=True)
    steals = Column(Integer, nullable=True)
    team_turnovers = Column(Integer, nullable=True)
    technical_fouls = Column(Integer, nullable=True)
    three_point_field_goal_pct = Column(Float, nullable=True)
    three_point_field_goals_made = Column(Integer, nullable=True)
    three_point_field_goals_attempted = Column(Integer, nullable=True)
    total_rebounds = Column(Integer, nullable=True)
    total_technical_fouls = Column(Integer, nullable=True)
    total_turnovers = Column(Integer, nullable=True)
    turnover_points = Column(Integer, nullable=True)
    turnovers = Column(Integer, nullable=True)
    opponent_team_id = Column(Integer, nullable=True)
    opponent_team_uid = Column(String(255), nullable=True)
    opponent_team_slug = Column(String(255), nullable=True)
    opponent_team_location = Column(String(255), nullable=True)
    opponent_team_name = Column(String(255), nullable=True)
    opponent_team_abbreviation = Column(String(255), nullable=True)
    opponent_team_display_name = Column(String(255), nullable=True)
    opponent_team_short_display_name = Column(String(255), nullable=True)
    opponent_team_color = Column(String(255), nullable=True)
    opponent_team_alternate_color = Column(String(255), nullable=True)
    opponent_team_logo = Column(String(255), nullable=True)
    opponent_team_score = Column(Integer, nullable=True)
